FROM cm2network/steamcmd:latest AS build

RUN /home/steam/steamcmd/steamcmd.sh +force_install_dir /home/steam/pz_server +login anonymous +app_update 380870 validate -beta build-39-vehicles +quit

RUN sed -i 's/"-Xmx768m",/"-XmxTEMP",/' /home/steam/pz_server/ProjectZomboid32.json

RUN sed -i 's/"-Xmx2048m",/"-XmxTEMP",/' /home/steam/pz_server/ProjectZomboid64.json

RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.home=/data",\' /home/steam/pz_server/ProjectZomboid32.json

RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.home=/data",\' /home/steam/pz_server/ProjectZomboid64.json


RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.language=TEMP",\' /home/steam/pz_server/ProjectZomboid32.json

RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.language=TEMP",\' /home/steam/pz_server/ProjectZomboid64.json
	

RUN sed -i '/INSTDIR="`pwd`"/ a\ulimit -n 4096\' /home/steam/pz_server/start-server.sh

FROM debian:12-slim

WORKDIR /app

RUN apt-get update && apt-get -y install ca-certificates gosu

COPY entrypoint.sh /entrypoint.sh
COPY run.sh /run.sh
COPY --from=build /home/steam/pz_server /app

RUN chmod +x /entrypoint.sh /run.sh

EXPOSE 16261/udp
EXPOSE 8766/udp
EXPOSE 8767/udp
EXPOSE 27015

VOLUME [ "/data" ]

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/run.sh"]
