services:
  app:
    container_name: project_zomboid_dedicated_server_build39-updatejre
    image: project-zomboid-dedicated-server:build39-updatejre
    build:
      dockerfile: dockerfile_build39-updatejre
    env_file: .env
    ports:
      - 16261:16261/udp #Default Port
      #- 8766:8766/udp #Steam 1 Port (only build 40)
      #- 8767:8767/udp #Steam 2 Port (only build 40)
      - 27015:27015 #Rcon
    volumes:
      - ./data:/data