FROM cm2network/steamcmd:latest AS build

RUN /home/steam/steamcmd/steamcmd.sh +force_install_dir /home/steam/pz_server +login anonymous +app_update 380870 validate -beta build-39-vehicles +quit

RUN sed -i 's/"-Xmx768m",/"-XmxTEMP",/' /home/steam/pz_server/ProjectZomboid32.json

RUN sed -i 's/"-Xmx2048m",/"-XmxTEMP",/' /home/steam/pz_server/ProjectZomboid64.json

RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.home=/data",\' /home/steam/pz_server/ProjectZomboid32.json

RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.home=/data",\' /home/steam/pz_server/ProjectZomboid64.json


RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.language=TEMP",\' /home/steam/pz_server/ProjectZomboid32.json

RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.language=TEMP",\' /home/steam/pz_server/ProjectZomboid64.json
	

RUN sed -i '/INSTDIR="`pwd`"/ a\ulimit -n 4096\' /home/steam/pz_server/start-server.sh

FROM debian:12-slim

WORKDIR /app

ENV UID=1000
ENV GID=1000

RUN apt-get update \
&& apt-get -y --no-install-suggests --no-install-recommends install ca-certificates \
&& groupadd -g ${GID} pzserver \
&& useradd -m -u ${UID} -g pzserver pzserver \
&& mkdir -p /data \
&& chown -R pzserver:pzserver /data \
&& chown -R pzserver:pzserver /app

COPY --chown=pzserver:pzserver run.sh /
COPY --from=build --chown=pzserver:pzserver /home/steam/pz_server /app

RUN chmod +x /run.sh

USER pzserver

EXPOSE 16261/udp
EXPOSE 8766/udp
EXPOSE 8767/udp
EXPOSE 27015

VOLUME [ "/data" ]

CMD [ "/run.sh" ]
