FROM debian:stable-slim

WORKDIR /app

#RUN apt-get update; \
#    apt-get -y install software-properties-common; \
#    apt-add-repository non-free; \
#    dpkg --add-architecture i386; \
#    apt-get update; \
#    apt-get -y install steamcmd

ARG VERSION_ID="12"

RUN apt-get update; \
    apt-get install -y lib32gcc-s1 curl; \
    curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -

RUN apt-get update; \
    apt-get -y install gosu


RUN apt-get update; \
    apt-get -y install wget; \
    wget -q https://packages.microsoft.com/config/debian/${VERSION_ID}/packages-microsoft-prod.deb; \
    dpkg -i packages-microsoft-prod.deb; \
    rm -f packages-microsoft-prod.deb; \
    apt-get update; \
    apt-get install -y powershell


COPY entrypoint.sh /entrypoint.sh
COPY run.ps1 /app/run.ps1
COPY functions.ps1 /app/functions.ps1

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["pwsh", "-ExecutionPolicy", "Bypass", "-File", "/app/run.ps1"]