FROM cm2network/steamcmd:latest AS build

RUN /home/steam/steamcmd/steamcmd.sh +force_install_dir /home/steam/pz_server +login anonymous +app_update 380870 validate -beta "38.30(pre-vehicles)" +quit

RUN sed -i 's/"-Xmx2048m",/"-XmxTEMP",/' /home/steam/pz_server/ProjectZomboid64.json


RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.language=TEMP",\' /home/steam/pz_server/ProjectZomboid64.json



RUN sed -i '/"-XmxTEMP",/ a\
	"-Ddeployment.user.cachedir=/data",\' /home/steam/pz_server/ProjectZomboid64.json



RUN sed -i '/INSTDIR="`pwd`"/ a\ulimit -n 4096\' /home/steam/pz_server/start-server.sh

RUN rm -Rf /home/steam/pz_server/jre
RUN rm -Rf /home/steam/pz_server/linux32
RUN rm -f /home/steam/pz_server/ProjectZomboid32.json
RUN rm -f /home/steam/pz_server/libpzexe_jni32.so
RUN rm -Rf /home/steam/pz_server/natives/*32.so
RUN rm -f /home/steam/pz_server/ProjectZomboid32

RUN rm -Rf /home/steam/pz_server/jre64

FROM debian:12 AS jre

ARG JRE_VERSION="8.88.0.19-ca-jre8.0.462"

WORKDIR /app

RUN apt-get update && apt-get install -y wget

RUN wget https://cdn.azul.com/zulu/bin/zulu${JRE_VERSION}-linux_x64.tar.gz

RUN tar -xf zulu${JRE_VERSION}-linux_x64.tar.gz

RUN mv zulu${JRE_VERSION}-linux_x64 jre64

FROM debian:12-slim

WORKDIR /app

RUN apt-get update && apt-get -y install ca-certificates gosu

COPY entrypoint.sh /entrypoint.sh
COPY run.sh /run.sh
COPY --from=build /home/steam/pz_server /app
COPY --from=jre /app/jre64 /app/jre64

RUN chmod +x /entrypoint.sh /run.sh

EXPOSE 16261/udp
EXPOSE 8766/udp
EXPOSE 8767/udp
EXPOSE 27015

VOLUME [ "/data" ]

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/run.sh"]
