FROM cm2network/steamcmd:latest AS build

RUN /home/steam/steamcmd/steamcmd.sh +force_install_dir /home/steam/pz_server +login anonymous +app_update 380870 validate -beta "38.30(pre-vehicles)" +quit

RUN sed -i 's/"-Xmx2048m",/"-XmxTEMP",/' /home/steam/pz_server/ProjectZomboid64.json


RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.language=TEMP",\' /home/steam/pz_server/ProjectZomboid64.json



RUN sed -i '/"-XmxTEMP",/ a\
	"-Ddeployment.user.cachedir=/data",\' /home/steam/pz_server/ProjectZomboid64.json



RUN sed -i '/INSTDIR="`pwd`"/ a\ulimit -n 4096\' /home/steam/pz_server/start-server.sh

RUN rm -Rf /home/steam/pz_server/jre
RUN rm -Rf /home/steam/pz_server/linux32
RUN rm -f /home/steam/pz_server/ProjectZomboid32.json
RUN rm -f /home/steam/pz_server/libpzexe_jni32.so
RUN rm -Rf /home/steam/pz_server/natives/*32.so
RUN rm -f /home/steam/pz_server/ProjectZomboid32

FROM debian:13.0-slim

ARG JRE_VERSION='"8.88.0.19-ca-jre8.0.462"'

WORKDIR /app

RUN apt-get update && apt-get -y install ca-certificates gosu wget

COPY entrypoint.sh /entrypoint.sh
COPY run.sh /run.sh
COPY --from=build /home/steam/pz_server /app

RUN sed -i "s/JRE_VERSION=/JRE_VERSION=${JRE_VERSION}/" /entrypoint.sh

RUN chmod +x /entrypoint.sh /run.sh

EXPOSE 16261/udp
EXPOSE 8766/udp
EXPOSE 8767/udp
EXPOSE 27015

VOLUME [ "/data" ]

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/run.sh"]
