FROM cm2network/steamcmd:latest AS build

RUN /home/steam/steamcmd/steamcmd.sh +force_install_dir /home/steam/pz_server +login anonymous +app_update 380870 validate +quit

#RUN sed -i 's/"-Xmx768m",/"-XmxTEMP",/' /home/steam/pz_server/ProjectZomboid32.json

RUN sed -i 's/"-Xmx8g",/"-XmxTEMP",/' /home/steam/pz_server/ProjectZomboid64.json


#RUN sed -i '/"-XmxTEMP",/ a\
#		"-Duser.language=TEMP",\' /home/steam/pz_server/ProjectZomboid32.json

RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.language=TEMP",\' /home/steam/pz_server/ProjectZomboid64.json


#RUN sed -i '/"-XmxTEMP",/ a\
#	"-Ddeployment.user.cachedir=/data",\' /home/steam/pz_server/ProjectZomboid32.json

RUN sed -i '/"-XmxTEMP",/ a\
	"-Ddeployment.user.cachedir=/data",\' /home/steam/pz_server/ProjectZomboid64.json


RUN rm -Rf /home/steam/pz_server/jre64

FROM debian:13 AS jre

ARG JRE_VERSION="17.60.17-ca-jre17.0.16"

WORKDIR /app

RUN apt-get update && apt-get install -y wget

RUN wget https://cdn.azul.com/zulu/bin/zulu${JRE_VERSION}-linux_x64.tar.gz

RUN tar -xf zulu${JRE_VERSION}-linux_x64.tar.gz

RUN mv zulu${JRE_VERSION}-linux_x64 jre64



FROM debian:13.0-slim

WORKDIR /app

RUN apt-get update && apt-get -y install ca-certificates gosu

COPY entrypoint.sh /entrypoint.sh
COPY run.sh /run.sh
COPY --from=build /home/steam/pz_server /app
COPY --from=jre /app/jre64 /app/jre64

RUN chmod +x /entrypoint.sh /run.sh

EXPOSE 16261/udp
EXPOSE 16262/udp
EXPOSE 27015

VOLUME [ "/data" ]

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/run.sh"]
