FROM cm2network/steamcmd:latest AS build

RUN /home/steam/steamcmd/steamcmd.sh +force_install_dir /home/steam/pz_server +login anonymous +app_update 380870 validate +quit

RUN sed -i 's/"-Xmx8g",/"-XmxTEMP",/' /home/steam/pz_server/ProjectZomboid64.json


RUN sed -i '/"-XmxTEMP",/ a\
		"-Duser.language=TEMP",\' /home/steam/pz_server/ProjectZomboid64.json


RUN sed -i '/"-XmxTEMP",/ a\
	"-Ddeployment.user.cachedir=/data",\' /home/steam/pz_server/ProjectZomboid64.json



RUN rm -f /home/steam/pz_server/ProjectZomboid32.json


FROM debian:13.0-slim

ARG JRE_VERSION='"17.60.17-ca-jre17.0.16"'

WORKDIR /app

RUN apt-get update && apt-get -y install ca-certificates gosu wget

COPY entrypoint.sh /entrypoint.sh
COPY run.sh /run.sh
COPY --from=build /home/steam/pz_server /app

RUN sed -i "s/JRE_VERSION=/JRE_VERSION=${JRE_VERSION}/" /entrypoint.sh

RUN chmod +x /entrypoint.sh /run.sh

EXPOSE 16261/udp
EXPOSE 16262/udp
EXPOSE 27015

VOLUME [ "/data" ]

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/run.sh"]
